### ISSUE TITLE
Site breaks when Context is updated

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Devops/isle-dc#178]
If you run a `composer update` and the latest version of Context is pulled in, the website stops working: "An unexpected error occurred".

Setting Context to an earlier version `composer require 'drupal/context:4.0-beta6'` brings the website back.

Need to figure out where the conflict is.

A snippet of my logs during the error:

```
drupal_1      | 2021/07/30 17:36:40 [error] 1006#1006: *3 FastCGI sent in stderr: "PHP message: ArgumentCountError: Too few arguments to function Drupal\context\ContextManager::__construct(), 5 passed in /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 and exactly 6 expected in /var/www/drupal/web/modules/contrib/context/src/ContextManager.php on line 108 #0 /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drupal\context\ContextManager->__construct()
drupal_1      | #1 /var/www/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService()
drupal_1      | #2 /var/www/drupal/web/core/lib/Drupal.php(158): Drupal\Component\DependencyInjection\Container->get()
drupal_1      | #3 /var/www/drupal/web/modules/contrib/islandora/islandora.module(273): Drupal::service()
drupal_1      | #4 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(539): islandora_entity_view_mode_alter()
drupal_1      | #5 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(191): Drupal\Core\Extension\ModuleHandler->alter()
drupal_1      | #6 /var/www/drupal/web/core/modules/node/src/NodeViewBuilder.php(61): Drupal\Core\Entity\EntityViewBuilder->getBuildDefaults()
drupal_1      | #7 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(168): Drupal\node\NodeViewBuilder->getBuildDefaults()
drupal_1      | #8 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(134): Drupal\Core\Entity\EntityViewBuilder->viewMultiple()
drupal_1      | #9 /var/www/drupal/web/core/lib/Drupal/Core/Entity/Controller/EntityViewController.php(105): Drupal\Core\Entity\EntityViewBuilder->view()
drupal_1      | #10 /var/www/drupal/web/core/modules/node/src/Controller/NodeViewController.php(71): Drupal\Core\Entity\Controller\EntityViewController->view()
drupal_1      | #11 [internal function]: Drupal\node\Controller\NodeViewController->view()
drupal_1      | #12 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
drupal_1      | #13 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(5
```

**Comment by bondjimbond** [comment]
From the tech call: apparently the best solution to this is to upgrade to Drupal 9. But there are some complexities, as a lot of the default modules and themes require Drupal 8.
