### ISSUE TITLE
make demo fails with PHP Fatal error:  Uncaught TypeError: array_filter() in search_api_solr

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-dc#362]
On latest tag=2.0.3 with fresh clone and `make clean`, then `make demo` build and Drupal install got to the point after importing 'islandora_tags' then failed with a `search_api_solr` error:
```
[notice] Processed 18 items (18 created, 0 updated, 0 failed, 0 ignored) - done with 'islandora_tags'
 [warning] Undefined array key "specific_languages" SearchApiSolrBackend.php:1195
PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /var/www/drupal/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php:1195
Stack trace:
#0 /var/www/drupal/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php(1195): array_filter()
#1 /var/www/drupal/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php(1118): Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend->getDocuments()
#2 /var/www/drupal/web/modules/contrib/search_api/src/Entity/Server.php(350): Drupal\search_api_solr\Plugin\search_api\backend\SearchApiSolrBackend->indexItems()
#3 /var/www/drupal/web/modules/contrib/search_api/src/Entity/Index.php(994): Drupal\search_api\Entity\Server->indexItems()
#4 /var/www/drupal/web/modules/contrib/search_api/src/Utility/PostRequestIndexing.php(92): Drupal\search_api\Entity\Index->indexSpecificItems()
#5 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/KernelDestructionSubscriber.php(51): Drupal\search_api\Utility\PostRequestIndexing->destruct()
#6 [internal function]: Drupal\Core\EventSubscriber\KernelDestructionSubscriber->onKernelTerminate()
#7 /var/www/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#8 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(103): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#9 /var/www/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\Component\HttpKernel\HttpKernel->terminate()
#10 /var/www/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(687): Stack\StackedHttpKernel->terminate()
#11 /var/www/drupal/vendor/drush/drush/src/Boot/DrupalBoot8.php(298): Drupal\Core\DrupalKernel->terminate()
#12 [internal function]: Drush\Boot\DrupalBoot8->terminate()
#13 {main}
  thrown in /var/www/drupal/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php on line 1195
make[2]: *** [run-islandora-migrations] Error 255
make[1]: *** [local] Error 2
make: *** [demo] Error 2

```

**Comment by kayakr** [comment]
FWIW, `docker compose exec -T drupal with-contenv bash -lc 'composer require "drupal/search_api_solr:4.3.0 as 4.2" -W'` worked to get Search API Solr working.

**Comment by joecorall** [comment]
The `make demo` command has been replaced by documentation.

```
$ make demo
make demo has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
